# Generated by Django 4.1.5 on 2023-01-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_path",
                    models.SlugField(
                        error_messages={
                            "unique": "Sorry, but this path is already taken."
                        },
                        max_length=255,
                        unique=True,
                        verbose_name="local path",
                    ),
                ),
                ("destination_url", models.URLField(verbose_name="destination url")),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="clicks"
                    ),
                ),
                (
                    "sender_ip",
                    models.GenericIPAddressField(
                        editable=False, null=True, verbose_name="sender IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
            ],
            options={
                "verbose_name": "redirect",
                "verbose_name_plural": "redirects",
            },
        ),
    ]
