dist: trusty
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database fakester;' -U postgres

install:
  - pip install -r requirements/dev.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --source fakester -m py.test
  - coverage report -m

after_success:
  - coveralls
