---
dist: trusty
suda: false
language: python

python:
  - '3.6'

addons:
  postgresql: '9.5'

before_install:
  - psql -c 'create database fakester;' -U postgres

install:
  - pip install tox tox-travis coveralls

script:
  - tox

after_success:
  - tox -e coverage-report
  - coveralls
