url: https://pawelad.xyz/fakester/
enforce_ssl: pawelad.xyz/fakester/

theme: jekyll-theme-dinky

gems:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
