version: "3.4"

x-common-variables: &common-variables
  DATABASE_URL: "postgres://postgres@db/fakester"
  REDIS_URL: "redis://redis:6379"

services:
  db:
    image: "postgres:15.1"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "fakester"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"

  redis:
    image: "redis:7.0"
    ports:
      - "6379:6379"

  app:
    build:
      context: "."
      target: "app"
    image: "fakester-app:latest"
    command: "--reload"
    environment: *common-variables
    env_file: ".env"
    volumes:
      - ".:/home/fakester/app"
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "redis"

  dev:
    build:
      context: "."
      target: "dev"
    image: "fakester-dev:latest"
    environment: *common-variables
    env_file: ".env"
    volumes:
      - ".:/home/fakester/app"
    depends_on:
      - "db"

volumes:
  postgres_data:
