[tool.black]
target-version = ["py311"]

[tool.coverage.run]
branch = true
source = ["src"]
omit = [
  "*/asgi.py",
  "*/manage.py",
  "*/migrations/*",
  "*/wsgi.py",
]

[tool.interrogate]
ignore-nested-classes = true
fail-under = 95
exclude = [
  "*/asgi.py",
  "*/manage.py",
  "*/migrations/*",
  "*/wsgi.py",
]

[tool.isort]
profile = "black"
src_paths = ["src"]
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --cov --verbose"
testpaths = "tests"
pythonpath = "src"
DJANGO_SETTINGS_MODULE = "fakester.settings"

[tool.ruff]
target-version = "py311"
select = [
  "A",  # flake8-builtins
  "ANN",  # flake8-annotations
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "C90",  # mccabe
  "D",  # pydocstyle
  "DJ",  # flake8-django
  "E",  # flake8
  "F",  # flake8
  "N",  # pep8-naming
  "PT",  # flake8-pytest-style
  "S",  # flake8-bandit
  "SIM",  # flake8-simplify
  "T20",  # flake8-print
  "TRY",  # tryceratops
  "UP",  # pyupgrade
]
ignore = [
  "ANN101",  # Missing type annotation for `self` in method
  "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in `**kwargs`
  "D106",  # Missing docstring in public nested class
  "S101",  # Use of `assert` detected
  "TRY003",  # Avoid specifying long messages outside the exception class
]
extend-exclude = ["migrations"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.11"
mypy_path = "src"
plugins = ["mypy_django_plugin.main"]
exclude = ["migrations"]

[[tool.mypy.overrides]]
module = [
  "crispy_forms.*",
  "decouple",
  "django_ratelimit.decorators",
  "ipware",
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "fakester.settings"
