[tool.black]
target-version = ["py310"]

[tool.isort]
profile = "black"
src_paths = ["src"]
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --verbose"
testpaths = "tests"
pythonpath = "src"
DJANGO_SETTINGS_MODULE = "fakester.settings"

[tool.ruff]
target-version = "py310"
select = [
  "E",  # flake8
  "F",  # flake8
#  "ANN",  # flake8-annotations
  "S",  # flake8-bandit
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "T20",  # flake8-print
  "PT",  # flake8-pytest-style
  "SIM",  # flake8-simplify
  "N",  # pep8-naming
#  "D",  # pydocstyle
]
ignore = [
  "S101",  # Use of `assert` detected
]
