[tool.black]
target-version = ["py310"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --verbose"
testpaths = "tests"
pythonpath = "src"
DJANGO_SETTINGS_MODULE = "fakester.settings"

[tool.isort]
profile = "black"
src_paths = ["src/fakester"]
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
