[tool.black]
target-version = ["py310"]

[tool.coverage.run]
branch = true
source = ["src"]
omit = [
  "*/asgi.py",
  "*/manage.py",
  "*/migrations/*",
  "*/wsgi.py",
]

[tool.isort]
profile = "black"
src_paths = ["src"]
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --cov --verbose"
testpaths = "tests"
pythonpath = "src"
DJANGO_SETTINGS_MODULE = "fakester.settings"

[tool.ruff]
target-version = "py310"
select = [
  "E",  # flake8
  "F",  # flake8
  "ANN",  # flake8-annotations
  "S",  # flake8-bandit
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "T20",  # flake8-print
  "PT",  # flake8-pytest-style
  "SIM",  # flake8-simplify
  "N",  # pep8-naming
#  "D",  # pydocstyle
]
ignore = [
  "ANN101",  # Missing type annotation for `self` in method
  "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in `**kwargs`
  "S101",  # Use of `assert` detected
]

[tool.mypy]
python_version = "3.10"
mypy_path = "src"
plugins = ["mypy_django_plugin.main"]
exclude = ["migrations"]

[[tool.mypy.overrides]]
module = [
  "crispy_forms.helper",
  "crispy_forms.layout",
  "decouple",
  "django_ratelimit.decorators",
  "ipware",
]
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "fakester.settings"
