# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 16:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('local_path', models.CharField(error_messages={'unique': 'Sorry, but this path is already taken.'}, max_length=256, unique=True, validators=[django.core.validators.RegexValidator(message='Allowed characters: a-z, A-Z, 0-9, slash (/), dot (.), underscore (_) and hyphen (-).', regex='[a-zA-Z0-9/._-]+')], verbose_name='local path')),
                ('destination_url', models.URLField(verbose_name='destination url')),
                ('clicks', models.PositiveIntegerField(default=0, editable=False, verbose_name='clicks')),
                ('sender_ip', models.GenericIPAddressField(editable=False, null=True, verbose_name='sender IP')),
            ],
            options={
                'verbose_name': 'redirect',
                'verbose_name_plural': 'redirects',
            },
        ),
    ]
