# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'redirect', 'verbose_name_plural': 'redirects'},
        ),
    ]
