---
name: "CI"

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHON_VERSION: "3.11"

jobs:
  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    services:
      db:
        image: "postgres:15.1"
        ports:
          - "5432:5432"
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup Python ${{ env.PYTHON_VERSION }}"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: "Update pip and install Nox"
        run: "python -m pip install pip nox -c requirements/constraints.txt"

      - name: "Run 'tests' Nox session"
        run: "nox -s tests"

  checks:
    strategy:
      matrix:
        include:
          - name: "Code style checks"
            nox_session: "code_style_checks"
          - name: "Type checks"
            nox_session: "type_checks"
          - name: "Django checks"
            nox_session: "django_checks"
    name: "${{ matrix.name }}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup Python ${{ env.PYTHON_VERSION }}"
        uses: "actions/setup-python@v4"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: "Update pip and install Nox"
        run: "python -m pip install pip nox -c requirements/constraints.txt"

      - name: "Run '${{ matrix.nox_session }}' Nox session"
        run: "nox -s ${{ matrix.nox_session }}"
