---
name: "Deploy"

on:
  release:
    types: ["published"]
  workflow_dispatch:

jobs:
  tests:
    name: "Run tests and checks"
    uses: "./.github/workflows/ci.yml"

  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    needs:
      - "tests"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Push to dokku"
        uses: "dokku/github-action@v1.4.0"
        with:
          branch: "main"
          git_remote_url: "${{ vars.DOKKU_GIT_REMOTE_URL }}"
          ssh_private_key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
